platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'EasyTurn' do
pod 'AFNetworking'
pod 'MJExtension'
#pod 'MJRefresh'
pod 'Masonry'
#pod 'SDCycleScrollView'
pod 'IQKeyboardManager'
pod 'YYModel'
pod 'STPopup'
pod 'DZNEmptyDataSet'
pod 'WechatOpenSDK'
pod 'JXCategoryView'
pod 'JXPagingView/Pager'
pod 'JXCategoryView'
# 高德定位SDK
pod 'AMapLocation'
pod 'EaseUILite', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'
pod 'AliyunOSSiOS'
pod 'JPush'
pod 'JJException'
pod 'BGFMDB','~>2.0.9'

end
